version: '3.8'

services:
  python_app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  node_app:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
